export interface Attraction {
  name: string;
  nameZh: string;
  image: string;
  description: string;
  descriptionZh: string;
  duration: string;
  durationZh: string;
  price: string;
  priceZh: string;
}

export interface Food {
  name: string;
  nameZh: string;
  image: string;
  description: string;
  descriptionZh: string;
  priceRange: string;
  priceRangeZh: string;
}

export interface TransportOption {
  mode: string;
  modeZh: string;
  description: string;
  descriptionZh: string;
  icon: string; // emoji
}

export interface QuickFact {
  label: string;
  labelZh: string;
  value: string;
  valueZh: string;
  icon: string; // emoji
}

export interface CityData {
  slug: string;
  name: string;
  nameZh: string;
  tagline: string;
  taglineZh: string;
  heroImage: string;
  quickFacts: QuickFact[];
  attractions: Attraction[];
  foods: Food[];
  transport: TransportOption[];
}

export const CITIES: CityData[] = [
  {
    slug: "beijing",
    name: "Beijing",
    nameZh: "北京",
    tagline: "The Imperial Capital — Where 3,000 Years of History Meet the Future",
    taglineZh: "千年帝都 — 三千年历史与未来在此交汇",
    heroImage: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=1920&h=1080&fit=crop&q=80",
    quickFacts: [
      { label: "Best Season", labelZh: "最佳季节", value: "Sep – Nov (Autumn)", valueZh: "9-11月（秋季）", icon: "🍂" },
      { label: "Avg Temperature", labelZh: "平均温度", value: "4°C – 26°C", valueZh: "4°C – 26°C", icon: "🌡️" },
      { label: "Currency", labelZh: "货币", value: "CNY (¥)", valueZh: "人民币 (¥)", icon: "💰" },
      { label: "Language", labelZh: "语言", value: "Mandarin Chinese", valueZh: "普通话", icon: "🗣️" },
      { label: "Time Zone", labelZh: "时区", value: "UTC+8", valueZh: "UTC+8（东八区）", icon: "🕐" },
      { label: "Visa", labelZh: "签证", value: "144h Transit Visa-Free", valueZh: "144小时过境免签", icon: "🛂" },
    ],
    attractions: [
      {
        name: "Forbidden City",
        nameZh: "故宫",
        image: "https://images.unsplash.com/photo-1584646098378-0874589d76b1?w=800&h=600&fit=crop",
        description: "The world's largest palace complex with 980 surviving buildings. Former home to 24 emperors across the Ming and Qing dynasties.",
        descriptionZh: "世界最大的宫殿建筑群，现存建筑980座。明清两代24位皇帝的居所。",
        duration: "3-4 hours",
        durationZh: "3-4小时",
        price: "¥60 (Apr-Oct) / ¥40 (Nov-Mar)",
        priceZh: "¥60（4-10月）/ ¥40（11-3月）",
      },
      {
        name: "Great Wall (Mutianyu)",
        nameZh: "长城（慕田峪）",
        image: "https://images.unsplash.com/photo-1508804052814-cd3ba865a116?w=800&h=600&fit=crop",
        description: "One of the best-preserved sections of the Great Wall, less crowded than Badaling. Features a cable car and toboggan ride down.",
        descriptionZh: "保存最完好的长城段落之一，比八达岭人少。有缆车和滑道下山。",
        duration: "Full day (4-6 hours on wall)",
        durationZh: "一整天（墙上4-6小时）",
        price: "¥40 + Cable car ¥120",
        priceZh: "¥40 + 缆车 ¥120",
      },
      {
        name: "Temple of Heaven",
        nameZh: "天坛",
        image: "https://images.unsplash.com/photo-1599571234909-29ed5d1321d6?w=800&h=600&fit=crop",
        description: "A masterpiece of Ming Dynasty architecture where emperors prayed for good harvests. The circular Hall of Prayer is iconic.",
        descriptionZh: "明代建筑杰作，皇帝在此祈求丰收。圆形的祈年殿是标志性建筑。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "¥15 (park) / ¥34 (full ticket)",
        priceZh: "¥15（公园）/ ¥34（联票）",
      },
      {
        name: "Summer Palace",
        nameZh: "颐和园",
        image: "https://images.unsplash.com/photo-1603852452515-2dc41d52cf44?w=800&h=600&fit=crop",
        description: "A vast ensemble of lakes, gardens, and palaces. The Long Corridor's 14,000+ painted scenes are a UNESCO treasure.",
        descriptionZh: "湖泊、园林与宫殿的宏大集合。长廊的14000多幅彩画是联合国教科文组织珍品。",
        duration: "3-4 hours",
        durationZh: "3-4小时",
        price: "¥30 (Apr-Oct) / ¥20 (Nov-Mar)",
        priceZh: "¥30（4-10月）/ ¥20（11-3月）",
      },
    ],
    foods: [
      {
        name: "Peking Duck",
        nameZh: "北京烤鸭",
        image: "https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=800&h=600&fit=crop",
        description: "Crispy-skinned duck carved tableside, wrapped in thin pancakes with scallions and hoisin sauce. Beijing's most iconic dish.",
        descriptionZh: "酥脆鸭皮在桌旁片切，配薄饼、葱丝和甜面酱。北京最具代表性的美食。",
        priceRange: "¥168 – ¥398 per duck",
        priceRangeZh: "¥168 – ¥398/只",
      },
      {
        name: "Zhajiangmian",
        nameZh: "炸酱面",
        image: "https://images.unsplash.com/photo-1555126634-323283e090fa?w=800&h=600&fit=crop",
        description: "Hand-pulled noodles topped with thick soybean paste sauce, diced pork, and fresh julienned vegetables. A true Beijing comfort food.",
        descriptionZh: "手工面条配浓厚的黄酱肉丁，搭配新鲜切丝蔬菜。真正的北京家常美味。",
        priceRange: "¥15 – ¥35",
        priceRangeZh: "¥15 – ¥35",
      },
      {
        name: "Jianbing (Savory Crêpe)",
        nameZh: "煎饼果子",
        image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&h=600&fit=crop",
        description: "A street-food staple — thin crêpe with egg, crispy wonton, scallions, and savory sauce. Best from morning cart vendors.",
        descriptionZh: "街头经典 — 薄脆饼配鸡蛋、酥脆馃篦、葱花和酱料。早餐摊的味道最正宗。",
        priceRange: "¥8 – ¥15",
        priceRangeZh: "¥8 – ¥15",
      },
    ],
    transport: [
      { mode: "Subway", modeZh: "地铁", description: "24 lines covering the entire city. ¥3-10 per ride. English signage throughout. Use Alipay QR to scan in.", descriptionZh: "24条线路覆盖全城。每次¥3-10。全程英文标识。支持支付宝扫码进站。", icon: "🚇" },
      { mode: "Bus", modeZh: "公交", description: "Extensive network but harder for non-Chinese speakers. ¥2 flat fare. Use transit card or Alipay.", descriptionZh: "网络覆盖广但对外国人较不友好。统一票价¥2。可用交通卡或支付宝。", icon: "🚌" },
      { mode: "DiDi (Ride-hailing)", modeZh: "滴滴（网约车）", description: "Like Uber. English app available. ¥15-50 for most city rides. Great for reaching the Great Wall.", descriptionZh: "类似Uber。有英文版App。市区大部分行程¥15-50。去长城很方便。", icon: "🚗" },
    ],
  },
  {
    slug: "shanghai",
    name: "Shanghai",
    nameZh: "上海",
    tagline: "The Paris of the East — Where Art Deco Meets Tomorrow's Skyline",
    taglineZh: "东方巴黎 — 装饰艺术与未来天际线的交汇",
    heroImage: "https://images.unsplash.com/photo-1545893835-abaa50cbe628?w=1920&h=1080&fit=crop&q=80",
    quickFacts: [
      { label: "Best Season", labelZh: "最佳季节", value: "Mar – May, Sep – Nov", valueZh: "3-5月、9-11月", icon: "🌸" },
      { label: "Avg Temperature", labelZh: "平均温度", value: "4°C – 32°C", valueZh: "4°C – 32°C", icon: "🌡️" },
      { label: "Currency", labelZh: "货币", value: "CNY (¥)", valueZh: "人民币 (¥)", icon: "💰" },
      { label: "Language", labelZh: "语言", value: "Mandarin & Shanghainese", valueZh: "普通话 & 上海话", icon: "🗣️" },
      { label: "Time Zone", labelZh: "时区", value: "UTC+8", valueZh: "UTC+8（东八区）", icon: "🕐" },
      { label: "Visa", labelZh: "签证", value: "144h Transit Visa-Free", valueZh: "144小时过境免签", icon: "🛂" },
    ],
    attractions: [
      {
        name: "The Bund",
        nameZh: "外滩",
        image: "https://images.unsplash.com/photo-1537531383496-67d0797d91c5?w=800&h=600&fit=crop",
        description: "Waterfront promenade with 52 heritage buildings showcasing Art Deco and Beaux-Arts architecture, facing Pudong's futuristic skyline.",
        descriptionZh: "滨江步道沿线52栋历史建筑，展示装饰艺术和学院派风格，对望浦东未来天际线。",
        duration: "1-2 hours",
        durationZh: "1-2小时",
        price: "Free",
        priceZh: "免费",
      },
      {
        name: "Yu Garden",
        nameZh: "豫园",
        image: "https://images.unsplash.com/photo-1567610479859-67e5b4549e4e?w=800&h=600&fit=crop",
        description: "A classical Chinese garden dating to 1559 with intricate rockeries, pavilions, and the famous Nine-Turn Bridge Zigzag Bridge.",
        descriptionZh: "始建于1559年的古典园林，精巧的假山、亭台楼阁和著名的九曲桥。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "¥40 (Apr-Jun, Sep-Nov) / ¥30 off-season",
        priceZh: "¥40（4-6月、9-11月）/ ¥30 淡季",
      },
      {
        name: "Oriental Pearl Tower",
        nameZh: "东方明珠",
        image: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&h=600&fit=crop",
        description: "Shanghai's iconic TV tower with observation decks, a glass-floor skywalk, and the Shanghai History Museum at the base.",
        descriptionZh: "上海标志性电视塔，设有观景台、玻璃天桥和底层的上海城市历史发展陈列馆。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "¥120 – ¥220",
        priceZh: "¥120 – ¥220",
      },
      {
        name: "Nanjing Road",
        nameZh: "南京路",
        image: "https://images.unsplash.com/photo-1581985673275-71a01a8a0a8f?w=800&h=600&fit=crop",
        description: "One of the world's busiest and longest shopping streets. The pedestrian East section stretches 1.2km with neon-lit shops and malls.",
        descriptionZh: "世界上最繁忙最长的购物街之一。步行街东段延伸1.2公里，霓虹闪烁。",
        duration: "2-4 hours",
        durationZh: "2-4小时",
        price: "Free (shopping optional)",
        priceZh: "免费（购物另计）",
      },
    ],
    foods: [
      {
        name: "Xiaolongbao (Soup Dumplings)",
        nameZh: "小笼包",
        image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&h=600&fit=crop",
        description: "Delicate steamed dumplings filled with hot soup and minced pork. Bite a small hole, slurp the soup, then eat. Shanghai's most famous dish.",
        descriptionZh: "精致的蒸笼小包，内含热汤和肉馅。先咬小口吸汤，再吃。上海最著名的美食。",
        priceRange: "¥30 – ¥80 per steamer",
        priceRangeZh: "¥30 – ¥80/笼",
      },
      {
        name: "Shengjianbao (Pan-fried Buns)",
        nameZh: "生煎包",
        image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&h=600&fit=crop",
        description: "Crispy-bottomed, soup-filled buns pan-fried in a giant skillet. Topped with sesame seeds and scallions. The ultimate street snack.",
        descriptionZh: "底部酥脆、内含汤汁的煎包，在大铁锅中煎制。撒上芝麻和葱花。终极街头小吃。",
        priceRange: "¥8 – ¥20 for 4 pieces",
        priceRangeZh: "¥8 – ¥20/4个",
      },
      {
        name: "Hairy Crab (Seasonal)",
        nameZh: "大闸蟹（季节性）",
        image: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=800&h=600&fit=crop",
        description: "Available Sep-Dec. Steamed whole and dipped in ginger-vinegar sauce. The rich, creamy roe is the highlight.",
        descriptionZh: "9-12月供应。整只清蒸蘸姜醋汁。浓郁细腻的蟹黄是精华所在。",
        priceRange: "¥80 – ¥300 per crab",
        priceRangeZh: "¥80 – ¥300/只",
      },
    ],
    transport: [
      { mode: "Metro", modeZh: "地铁", description: "19 lines, the world's longest metro network. ¥3-9 per ride. English on all displays.", descriptionZh: "19条线路，世界最长的地铁网络。每次¥3-9。所有显示屏有英文。", icon: "🚇" },
      { mode: "Maglev Train", modeZh: "磁悬浮", description: "World's fastest commercial train at 431 km/h. Pudong Airport → Longyang Road in 7 min. ¥50 single.", descriptionZh: "世界最快的商业列车，时速431公里。浦东机场→龙阳路7分钟。单程¥50。", icon: "🚄" },
      { mode: "DiDi / Taxi", modeZh: "滴滴/出租车", description: "Taxis are plentiful. Start at ¥14. DiDi app works great with English UI.", descriptionZh: "出租车很多。起步价¥14。滴滴App有英文界面，非常好用。", icon: "🚗" },
    ],
  },
  {
    slug: "chengdu",
    name: "Chengdu",
    nameZh: "成都",
    tagline: "Land of Abundance — Giant Pandas, Fiery Hotpot & Chill Vibes",
    taglineZh: "天府之国 — 大熊猫、麻辣火锅与悠闲生活",
    heroImage: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=1920&h=1080&fit=crop&q=80",
    quickFacts: [
      { label: "Best Season", labelZh: "最佳季节", value: "Mar – Jun, Sep – Nov", valueZh: "3-6月、9-11月", icon: "🌿" },
      { label: "Avg Temperature", labelZh: "平均温度", value: "5°C – 30°C", valueZh: "5°C – 30°C", icon: "🌡️" },
      { label: "Currency", labelZh: "货币", value: "CNY (¥)", valueZh: "人民币 (¥)", icon: "💰" },
      { label: "Language", labelZh: "语言", value: "Mandarin & Sichuan dialect", valueZh: "普通话 & 四川话", icon: "🗣️" },
      { label: "Time Zone", labelZh: "时区", value: "UTC+8", valueZh: "UTC+8（东八区）", icon: "🕐" },
      { label: "Visa", labelZh: "签证", value: "144h Transit Visa-Free", valueZh: "144小时过境免签", icon: "🛂" },
    ],
    attractions: [
      {
        name: "Giant Panda Breeding Research Base",
        nameZh: "大熊猫繁育研究基地",
        image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&h=600&fit=crop",
        description: "Home to 200+ giant pandas. See adults munching bamboo, red pandas playing, and (if lucky) newborn cubs in the nursery.",
        descriptionZh: "200多只大熊猫的家。看成年大熊猫啃竹子、小熊猫玩耍，运气好还能看到育婴室的幼崽。",
        duration: "3-4 hours",
        durationZh: "3-4小时",
        price: "¥55",
        priceZh: "¥55",
      },
      {
        name: "Jinli Ancient Street",
        nameZh: "锦里古街",
        image: "https://images.unsplash.com/photo-1626690074592-46a07a60e4f6?w=800&h=600&fit=crop",
        description: "A lively pedestrian street with traditional Sichuan architecture, street food stalls, tea houses, and Shu brocade shops.",
        descriptionZh: "热闹的步行街，传统四川建筑、街头小吃、茶馆和蜀锦商店。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "Free entry",
        priceZh: "免费入场",
      },
      {
        name: "Kuanzhai Alley",
        nameZh: "宽窄巷子",
        image: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800&h=600&fit=crop",
        description: "Three parallel alleys from the Qing Dynasty era — Wide Alley, Narrow Alley, and Well Alley. A perfect blend of old and new Chengdu.",
        descriptionZh: "三条清代平行巷子 — 宽巷子、窄巷子、井巷子。新旧成都的完美融合。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "Free entry",
        priceZh: "免费入场",
      },
    ],
    foods: [
      {
        name: "Sichuan Hotpot",
        nameZh: "四川火锅",
        image: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=800&h=600&fit=crop",
        description: "Bubbling pot of chili oil and Sichuan peppercorn broth where you cook meats, vegetables, and tofu. Choose spicy or split pot (half spicy, half mild).",
        descriptionZh: "翻滚的辣椒油和花椒锅底，涮煮肉类、蔬菜和豆腐。可选全辣或鸳鸯锅（半辣半清汤）。",
        priceRange: "¥80 – ¥150 per person",
        priceRangeZh: "¥80 – ¥150/人",
      },
      {
        name: "Chuanchuan (Skewer Hotpot)",
        nameZh: "串串香",
        image: "https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&h=600&fit=crop",
        description: "Street-style hotpot — pick bamboo skewers with different ingredients, dip them in a shared spicy pot, and pay by the skewer. Cheap and addictive!",
        descriptionZh: "街头风格火锅 — 自选竹签串好的食材，放入共用的辣锅中涮煮，按签数计费。便宜又上瘾！",
        priceRange: "¥0.5 – ¥3 per skewer",
        priceRangeZh: "¥0.5 – ¥3/串",
      },
      {
        name: "Mapo Tofu",
        nameZh: "麻婆豆腐",
        image: "https://images.unsplash.com/photo-1582450871972-ab5ca641643d?w=800&h=600&fit=crop",
        description: "Silky tofu in a fiery sauce of chili bean paste, minced pork, and tongue-numbing Sichuan peppercorn. A Chengdu classic since 1862.",
        descriptionZh: "嫩滑豆腐配辣豆瓣酱、肉末和麻得舌头发麻的花椒。成都经典名菜，始于1862年。",
        priceRange: "¥18 – ¥38",
        priceRangeZh: "¥18 – ¥38",
      },
    ],
    transport: [
      { mode: "Metro", modeZh: "地铁", description: "13 lines. Clean and efficient. ¥2-7 per ride. All stations have English signage.", descriptionZh: "13条线路。干净高效。每次¥2-7。所有车站有英文标识。", icon: "🚇" },
      { mode: "Bus", modeZh: "公交", description: "Extensive coverage. ¥2 per ride. Download Alipay for easy payment.", descriptionZh: "覆盖广泛。每次¥2。下载支付宝方便支付。", icon: "🚌" },
      { mode: "DiDi (Ride-hailing)", modeZh: "滴滴（网约车）", description: "Widely available and affordable. ¥10-30 for most trips. Essential for reaching the Panda Base.", descriptionZh: "普及且实惠。大部分行程¥10-30。去熊猫基地必备。", icon: "🚗" },
    ],
  },
  {
    slug: "xian",
    name: "Xi'an",
    nameZh: "西安",
    tagline: "The Eternal City — Gateway to the Silk Road & the Terracotta Army",
    taglineZh: "永恒之城 — 丝绸之路的起点与兵马俑的故乡",
    heroImage: "https://images.unsplash.com/photo-1725933014999-e70ae6e57375?w=1920&h=1080&fit=crop&q=80",
    quickFacts: [
      { label: "Best Season", labelZh: "最佳季节", value: "Apr – May, Sep – Oct", valueZh: "4-5月、9-10月", icon: "🏯" },
      { label: "Avg Temperature", labelZh: "平均温度", value: "-1°C – 32°C", valueZh: "-1°C – 32°C", icon: "🌡️" },
      { label: "Currency", labelZh: "货币", value: "CNY (¥)", valueZh: "人民币 (¥)", icon: "💰" },
      { label: "Language", labelZh: "语言", value: "Mandarin & Shaanxi dialect", valueZh: "普通话 & 陕西话", icon: "🗣️" },
      { label: "Time Zone", labelZh: "时区", value: "UTC+8", valueZh: "UTC+8（东八区）", icon: "🕐" },
      { label: "Visa", labelZh: "签证", value: "144h Transit Visa-Free", valueZh: "144小时过境免签", icon: "🛂" },
    ],
    attractions: [
      {
        name: "Terracotta Warriors",
        nameZh: "兵马俑",
        image: "https://images.unsplash.com/photo-1591018653367-e685d3019875?w=800&h=600&fit=crop",
        description: "An army of 8,000 life-sized clay soldiers buried for 2,200 years to guard Emperor Qin Shi Huang in the afterlife. A UNESCO World Heritage Site.",
        descriptionZh: "8000个真人大小的陶俑军团，埋藏2200年，守护秦始皇的来世。联合国教科文组织世界遗产。",
        duration: "3-4 hours",
        durationZh: "3-4小时",
        price: "¥120",
        priceZh: "¥120",
      },
      {
        name: "Ancient City Wall",
        nameZh: "古城墙",
        image: "https://images.unsplash.com/photo-1565018045502-44ab3db18c2a?w=800&h=600&fit=crop",
        description: "The best-preserved ancient city wall in China, 13.7km around. Rent a bike and cycle the full loop for stunning sunset views.",
        descriptionZh: "中国保存最完好的古城墙，周长13.7公里。租辆自行车骑一圈，欣赏绝美落日。",
        duration: "2-3 hours (cycling)",
        durationZh: "2-3小时（骑行）",
        price: "¥54 + Bike rental ¥45",
        priceZh: "¥54 + 自行车租赁 ¥45",
      },
      {
        name: "Muslim Quarter",
        nameZh: "回民街",
        image: "https://images.unsplash.com/photo-1564769662533-4f00a87b4056?w=800&h=600&fit=crop",
        description: "A vibrant food street with centuries of Hui Muslim heritage. Sizzling lamb skewers, pomegranate juice, and the iconic Drum Tower nearby.",
        descriptionZh: "充满活力的美食街，有着数百年回族文化遗产。滋滋作响的羊肉串、石榴汁，标志性的鼓楼近在咫尺。",
        duration: "2-4 hours",
        durationZh: "2-4小时",
        price: "Free (food ¥5-30/item)",
        priceZh: "免费（美食 ¥5-30/样）",
      },
      {
        name: "Big Wild Goose Pagoda",
        nameZh: "大雁塔",
        image: "https://images.unsplash.com/photo-1610972049438-40e3fce69ad5?w=800&h=600&fit=crop",
        description: "A 7-story Tang Dynasty pagoda built in 652 AD. The surrounding plaza has Asia's largest musical fountain show (free, evenings).",
        descriptionZh: "始建于公元652年的七层唐代宝塔。周围广场有亚洲最大的音乐喷泉秀（免费，晚间）。",
        duration: "1-2 hours",
        durationZh: "1-2小时",
        price: "¥40",
        priceZh: "¥40",
      },
    ],
    foods: [
      {
        name: "Roujiamo (Chinese Burger)",
        nameZh: "肉夹馍",
        image: "https://images.unsplash.com/photo-1643123446139-1b05e90e3f5e?w=800&h=600&fit=crop",
        description: "Slow-braised pork belly stuffed into a crispy flatbread. Often called 'China's oldest hamburger' — and it's been around for 2,000 years.",
        descriptionZh: "慢炖猪肉夹在酥脆的白吉馍中。常被称为「中国最古老的汉堡」 — 已有2000年历史。",
        priceRange: "¥8 – ¥15",
        priceRangeZh: "¥8 – ¥15",
      },
      {
        name: "Liangpi (Cold Noodles)",
        nameZh: "凉皮",
        image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=600&fit=crop",
        description: "Chewy cold rice noodles in chili oil, vinegar, and sesame sauce with cucumber and bean sprouts. The perfect refreshing snack.",
        descriptionZh: "弹牙凉爽的米皮配辣椒油、醋和芝麻酱，加黄瓜丝和豆芽。完美的解暑小吃。",
        priceRange: "¥8 – ¥15",
        priceRangeZh: "¥8 – ¥15",
      },
      {
        name: "Yangrou Paomo (Lamb Soup)",
        nameZh: "羊肉泡馍",
        image: "https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&h=600&fit=crop",
        description: "Rich lamb broth poured over hand-torn flatbread pieces. You tear the bread yourself — the smaller the pieces, the better the flavor.",
        descriptionZh: "浓郁的羊肉汤浇在手撕的馍块上。馍要自己掰 — 掰得越碎越入味。",
        priceRange: "¥25 – ¥45",
        priceRangeZh: "¥25 – ¥45",
      },
    ],
    transport: [
      { mode: "Metro", modeZh: "地铁", description: "8 lines with English signs. ¥2-6 per ride. Line 2 connects train station to most attractions.", descriptionZh: "8条线路有英文标识。每次¥2-6。2号线连接火车站和大部分景点。", icon: "🚇" },
      { mode: "Tourist Bus", modeZh: "旅游巴士", description: "Special buses run to Terracotta Warriors from the train station (Bus 306/914). ¥7, takes ~1 hour.", descriptionZh: "有专线巴士从火车站到兵马俑（306/914路）。¥7，约1小时。", icon: "🚌" },
      { mode: "DiDi / Taxi", modeZh: "滴滴/出租车", description: "Taxis start at ¥9. DiDi is reliable. City center is compact and easy to navigate.", descriptionZh: "出租车起步价¥9。滴滴可靠。市中心紧凑，容易导航。", icon: "🚗" },
    ],
  },
  {
    slug: "guilin",
    name: "Guilin",
    nameZh: "桂林",
    tagline: "Mountains & Rivers Like a Painting — China's Most Breathtaking Landscape",
    taglineZh: "桂林山水甲天下 — 中国最令人惊叹的自然画卷",
    heroImage: "https://images.unsplash.com/photo-1759322451543-68c2217e9046?w=1920&h=1080&fit=crop&q=80",
    quickFacts: [
      { label: "Best Season", labelZh: "最佳季节", value: "Apr – Oct", valueZh: "4-10月", icon: "🌾" },
      { label: "Avg Temperature", labelZh: "平均温度", value: "8°C – 33°C", valueZh: "8°C – 33°C", icon: "🌡️" },
      { label: "Currency", labelZh: "货币", value: "CNY (¥)", valueZh: "人民币 (¥)", icon: "💰" },
      { label: "Language", labelZh: "语言", value: "Mandarin & Guilin dialect", valueZh: "普通话 & 桂林话", icon: "🗣️" },
      { label: "Time Zone", labelZh: "时区", value: "UTC+8", valueZh: "UTC+8（东八区）", icon: "🕐" },
      { label: "Visa", labelZh: "签证", value: "144h Transit Visa-Free", valueZh: "144小时过境免签", icon: "🛂" },
    ],
    attractions: [
      {
        name: "Li River Cruise",
        nameZh: "漓江游船",
        image: "https://images.unsplash.com/photo-1529921879218-f99546d03caa?w=800&h=600&fit=crop",
        description: "A 4-5 hour boat cruise from Guilin to Yangshuo through towering karst peaks, bamboo groves, and water buffalo along the riverbanks.",
        descriptionZh: "4-5小时的游船从桂林到阳朔，穿越高耸的喀斯特山峰、竹林和水牛点缀的河岸。",
        duration: "4-5 hours",
        durationZh: "4-5小时",
        price: "¥210 – ¥450",
        priceZh: "¥210 – ¥450",
      },
      {
        name: "Yangshuo",
        nameZh: "阳朔",
        image: "https://images.unsplash.com/photo-1528803376441-5aafad4e63e5?w=800&h=600&fit=crop",
        description: "A charming riverside town surrounded by karst peaks. Rent a bike, bamboo raft on the Yulong River, or watch the Impression Liu Sanjie show.",
        descriptionZh: "被喀斯特群峰环绕的迷人小镇。骑车漫游、遇龙河竹筏漂流，或观看印象刘三姐演出。",
        duration: "1-2 days",
        durationZh: "1-2天",
        price: "Free (activities ¥50-200)",
        priceZh: "免费（活动 ¥50-200）",
      },
      {
        name: "Longji Rice Terraces",
        nameZh: "龙脊梯田",
        image: "https://images.unsplash.com/photo-1620984438691-1d60f0777ecc?w=800&h=600&fit=crop",
        description: "Stunning terraced rice paddies carved into mountainsides over 700 years. Visit Ping'an or Jinkeng villages for panoramic hiking.",
        descriptionZh: "壮观的梯田稻作，700多年雕刻于山间。去平安或金坑村寨，享受全景徒步。",
        duration: "Full day or overnight",
        durationZh: "一整天或过夜",
        price: "¥80",
        priceZh: "¥80",
      },
    ],
    foods: [
      {
        name: "Guilin Rice Noodles",
        nameZh: "桂林米粉",
        image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&h=600&fit=crop",
        description: "Smooth round rice noodles in a savory broth with braised beef, pickled vegetables, and chili. Every local has their favorite stall.",
        descriptionZh: "爽滑的圆米粉配鲜美卤汤、卤牛肉、酸豆角和辣椒。每个本地人都有自己最爱的粉店。",
        priceRange: "¥8 – ¥20",
        priceRangeZh: "¥8 – ¥20",
      },
      {
        name: "Beer Fish (Yangshuo specialty)",
        nameZh: "啤酒鱼（阳朔特色）",
        image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&h=600&fit=crop",
        description: "Fresh Li River fish braised in local beer with tomatoes, peppers, and garlic. Best enjoyed at a riverside restaurant in Yangshuo.",
        descriptionZh: "新鲜漓江鱼用当地啤酒炖煮，配番茄、辣椒和大蒜。在阳朔河边餐厅品尝最佳。",
        priceRange: "¥60 – ¥120",
        priceRangeZh: "¥60 – ¥120",
      },
      {
        name: "Oil Tea",
        nameZh: "油茶",
        image: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=800&h=600&fit=crop",
        description: "A traditional Guilin drink — ground tea, ginger, and peanuts pounded together and brewed. Savory, warming, and uniquely local.",
        descriptionZh: "桂林传统饮品 — 茶叶、生姜和花生一起捶打冲泡。咸香暖胃，独特的地方风味。",
        priceRange: "¥5 – ¥15",
        priceRangeZh: "¥5 – ¥15",
      },
    ],
    transport: [
      { mode: "Shuttle Bus", modeZh: "旅游大巴", description: "Regular shuttles between Guilin and Yangshuo. ¥25-30, ~1.5 hours. Also to Longji Terraces.", descriptionZh: "桂林和阳朔间有定期班车。¥25-30，约1.5小时。也有去龙脊梯田的班车。", icon: "🚌" },
      { mode: "Bamboo Raft", modeZh: "竹筏", description: "Float down the Yulong River on a bamboo raft (motorized). ¥200-300 for 1.5-2 hours. Peaceful and scenic.", descriptionZh: "乘竹筏（机动）漂流遇龙河。¥200-300/1.5-2小时。宁静而风景如画。", icon: "🛶" },
      { mode: "Electric Scooter", modeZh: "电动车", description: "Rent an e-scooter in Yangshuo for ¥50-80/day. The best way to explore the countryside at your own pace.", descriptionZh: "在阳朔租电动车¥50-80/天。按自己的节奏探索乡村的最佳方式。", icon: "🛵" },
    ],
  },
  {
    slug: "hongkong",
    name: "Hong Kong",
    nameZh: "香港",
    tagline: "Asia's World City — Harbour Views, Dim Sum & Neon-Lit Streets",
    taglineZh: "亚洲国际都会 — 维港美景、点心飘香、霓虹街市",
    heroImage: "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=1920&h=1080&fit=crop&q=80",
    quickFacts: [
      { label: "Best Season", labelZh: "最佳季节", value: "Oct – Dec (Autumn)", valueZh: "10-12月（秋季）", icon: "🌤️" },
      { label: "Avg Temperature", labelZh: "平均温度", value: "15°C – 33°C", valueZh: "15°C – 33°C", icon: "🌡️" },
      { label: "Currency", labelZh: "货币", value: "HKD (HK$)", valueZh: "港币 (HK$)", icon: "💰" },
      { label: "Language", labelZh: "语言", value: "Cantonese, English, Mandarin", valueZh: "粤语、英语、普通话", icon: "🗣️" },
      { label: "Time Zone", labelZh: "时区", value: "UTC+8", valueZh: "UTC+8（东八区）", icon: "🕐" },
      { label: "Visa", labelZh: "签证", value: "Visa-free for 170+ countries", valueZh: "170多个国家免签", icon: "🛂" },
    ],
    attractions: [
      {
        name: "Victoria Harbour",
        nameZh: "维多利亚港",
        image: "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800&h=600&fit=crop",
        description: "The iconic harbour between Hong Kong Island and Kowloon. Take the Star Ferry (HK$2.70!), watch the Symphony of Lights show at 8PM nightly.",
        descriptionZh: "香港岛与九龙之间的标志性海港。乘天星小轮（HK$2.70！），每晚8点观看幻彩咏香江灯光秀。",
        duration: "1-2 hours",
        durationZh: "1-2小时",
        price: "Star Ferry HK$2.70",
        priceZh: "天星小轮 HK$2.70",
      },
      {
        name: "Victoria Peak",
        nameZh: "太平山顶",
        image: "https://images.unsplash.com/photo-1506970845246-9f0c8f05aaec?w=800&h=600&fit=crop",
        description: "Take the Peak Tram up for the best panoramic view of the city, harbour, and Kowloon. Sky Terrace 428 offers 360° views.",
        descriptionZh: "乘山顶缆车上山，俯瞰城市、海港和九龙的最佳全景。凌霄阁428观景台提供360°美景。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "Peak Tram HK$62 / Sky Terrace HK$75",
        priceZh: "山顶缆车 HK$62 / 凌霄阁 HK$75",
      },
      {
        name: "Temple Street Night Market",
        nameZh: "庙街夜市",
        image: "https://images.unsplash.com/photo-1553701879-85b5abb7b76d?w=800&h=600&fit=crop",
        description: "Kowloon's most famous night market. Browse bargain clothes, electronics, and jade, then sit down for street-side claypot rice or seafood.",
        descriptionZh: "九龙最著名的夜市。淘便宜衣服、电子产品和玉器，然后坐下来吃街边煲仔饭或海鲜。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "Free entry",
        priceZh: "免费入场",
      },
    ],
    foods: [
      {
        name: "Dim Sum",
        nameZh: "点心",
        image: "https://images.unsplash.com/photo-1576577445504-6af96477db52?w=800&h=600&fit=crop",
        description: "The art of Cantonese brunch — steamer baskets of har gow (shrimp dumplings), siu mai (pork dumplings), char siu bao (BBQ pork buns), and dozens more.",
        descriptionZh: "广式早茶的艺术 — 一笼笼虾饺、烧麦、叉烧包，以及更多精致点心。",
        priceRange: "HK$80 – HK$300 per person",
        priceRangeZh: "HK$80 – HK$300/人",
      },
      {
        name: "Pineapple Bun (Bolo Bao)",
        nameZh: "菠萝油",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop",
        description: "Warm, crumbly-topped bun with a thick slab of cold butter melting inside. A classic cha chaan teng (Hong Kong café) treat. No actual pineapple!",
        descriptionZh: "温热的酥皮面包夹一大块冷黄油在里面融化。经典的茶餐厅美味。其实没有菠萝！",
        priceRange: "HK$10 – HK$25",
        priceRangeZh: "HK$10 – HK$25",
      },
      {
        name: "Egg Waffle (Gai Dan Jai)",
        nameZh: "鸡蛋仔",
        image: "https://images.unsplash.com/photo-1582564286960-0a4a7ffe5e42?w=800&h=600&fit=crop",
        description: "Crispy-outside, soft-inside egg-shaped waffle puffs. A Hong Kong street food icon since the 1950s. Find them at corner stalls everywhere.",
        descriptionZh: "外脆内软的蛋形华夫饼。自1950年代起就是香港街头美食的标志。街角随处可见。",
        priceRange: "HK$20 – HK$40",
        priceRangeZh: "HK$20 – HK$40",
      },
    ],
    transport: [
      { mode: "MTR (Subway)", modeZh: "港铁", description: "Fast, clean, and English-friendly. Octopus Card for contactless payment. HK$5-55 per ride. Covers the entire city.", descriptionZh: "快速、干净、英文友好。八达通卡无接触支付。每次HK$5-55。覆盖全城。", icon: "🚇" },
      { mode: "Star Ferry", modeZh: "天星小轮", description: "Iconic harbour crossing between Central and Tsim Sha Tsui. HK$2.70. A must-do experience, not just transport.", descriptionZh: "标志性的海港渡轮，往返中环和尖沙咀。HK$2.70。不只是交通，更是必做体验。", icon: "⛴️" },
      { mode: "Taxi / Bus / Tram", modeZh: "出租车/巴士/电车", description: "Red taxis for urban HK$27 start. Iconic double-decker trams on HK Island HK$3. Extensive bus network.", descriptionZh: "市区红色出租车起步HK$27。港岛标志性双层电车HK$3。公交网络覆盖广泛。", icon: "🚕" },
    ],
  },
  {
    slug: "hangzhou",
    name: "Hangzhou",
    nameZh: "杭州",
    tagline: "Heaven on Earth — West Lake, Tea Culture & China's Tech Capital",
    taglineZh: "人间天堂 — 西湖美景、茶韵飘香、科技之都",
    heroImage: "https://images.unsplash.com/photo-1599571234909-29ed5d1321d6?w=1920&h=1080&fit=crop&q=80",
    quickFacts: [
      { label: "Best Season", labelZh: "最佳季节", value: "Mar – May, Sep – Nov", valueZh: "3-5月、9-11月", icon: "🌸" },
      { label: "Avg Temperature", labelZh: "平均温度", value: "4°C – 33°C", valueZh: "4°C – 33°C", icon: "🌡️" },
      { label: "Currency", labelZh: "货币", value: "CNY (¥)", valueZh: "人民币 (¥)", icon: "💰" },
      { label: "Language", labelZh: "语言", value: "Mandarin & Hangzhou dialect", valueZh: "普通话 & 杭州话", icon: "🗣️" },
      { label: "Time Zone", labelZh: "时区", value: "UTC+8", valueZh: "UTC+8（东八区）", icon: "🕐" },
      { label: "Visa", labelZh: "签证", value: "144h Transit Visa-Free", valueZh: "144小时过境免签", icon: "🛂" },
    ],
    attractions: [
      {
        name: "West Lake",
        nameZh: "西湖",
        image: "https://images.unsplash.com/photo-1599571234909-29ed5d1321d6?w=800&h=600&fit=crop",
        description: "A UNESCO World Heritage Site and the heart of Hangzhou. Stroll the Su Causeway, boat across serene waters, and admire centuries of Chinese garden art.",
        descriptionZh: "联合国教科文组织世界遗产，杭州的灵魂。漫步苏堤、泛舟湖上，欣赏千年中国园林艺术。",
        duration: "3-5 hours",
        durationZh: "3-5小时",
        price: "Free (boat ¥45-150)",
        priceZh: "免费（游船 ¥45-150）",
      },
      {
        name: "Lingyin Temple",
        nameZh: "灵隐寺",
        image: "https://images.unsplash.com/photo-1603852452515-2dc41d52cf44?w=800&h=600&fit=crop",
        description: "One of China's oldest and most renowned Buddhist temples, founded in 328 AD. Explore the Feilai Feng grottoes with 470+ stone carvings.",
        descriptionZh: "中国最古老、最著名的佛教寺院之一，始建于公元328年。探索飞来峰石窟的470多尊石刻造像。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "¥75 (park + temple)",
        priceZh: "¥75（景区+寺院）",
      },
      {
        name: "Longjing Tea Plantations",
        nameZh: "龙井茶园",
        image: "https://images.unsplash.com/photo-1556881286-fc6915169721?w=800&h=600&fit=crop",
        description: "Visit the birthplace of China's most famous green tea. Walk through terraced tea fields, watch hand-roasting demonstrations, and taste fresh Longjing.",
        descriptionZh: "探访中国最著名绿茶的发源地。穿行梯田茶园，观看手工炒制演示，品尝新鲜龙井。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "Free (tea tasting ¥30-100)",
        priceZh: "免费（品茶 ¥30-100）",
      },
      {
        name: "Hefang Street",
        nameZh: "河坊街",
        image: "https://images.unsplash.com/photo-1626690074592-46a07a60e4f6?w=800&h=600&fit=crop",
        description: "A lively pedestrian street dating back to the Southern Song Dynasty. Traditional medicine shops, handicrafts, street performers, and classic Hangzhou snacks.",
        descriptionZh: "热闹的步行街，可追溯至南宋。传统中药铺、手工艺品、街头表演和经典杭州小吃。",
        duration: "1-2 hours",
        durationZh: "1-2小时",
        price: "Free entry",
        priceZh: "免费入场",
      },
      {
        name: "Xixi Wetland Park",
        nameZh: "西溪湿地",
        image: "https://images.unsplash.com/photo-1528803376441-5aafad4e63e5?w=800&h=600&fit=crop",
        description: "China's first national wetland park — 11 sq km of waterways, bamboo groves, and persimmon orchards. Take a traditional boat ride through the misty channels.",
        descriptionZh: "中国第一个国家湿地公园 — 11平方公里的水道、竹林和柿子园。乘传统小船穿行雾中水道。",
        duration: "3-4 hours",
        durationZh: "3-4小时",
        price: "¥80",
        priceZh: "¥80",
      },
    ],
    foods: [
      {
        name: "Dongpo Pork",
        nameZh: "东坡肉",
        image: "https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=800&h=600&fit=crop",
        description: "Braised pork belly slow-cooked in Shaoxing wine, soy sauce, and sugar until meltingly tender. Named after poet Su Dongpo. Hangzhou's signature dish.",
        descriptionZh: "五花肉用绍兴酒、酱油和糖慢炖至入口即化。以诗人苏东坡命名。杭州招牌菜。",
        priceRange: "¥38 – ¥68",
        priceRangeZh: "¥38 – ¥68",
      },
      {
        name: "West Lake Vinegar Fish",
        nameZh: "西湖醋鱼",
        image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&h=600&fit=crop",
        description: "Fresh grass carp poached and glazed with a sweet-and-sour vinegar sauce. The sauce is delicate — not heavy. A quintessential Hangzhou taste.",
        descriptionZh: "新鲜草鱼水煮后淋上酸甜醋汁。酱汁精致而不厚重。最经典的杭州味道。",
        priceRange: "¥58 – ¥108",
        priceRangeZh: "¥58 – ¥108",
      },
      {
        name: "Longjing Shrimp",
        nameZh: "龙井虾仁",
        image: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&h=600&fit=crop",
        description: "Plump river shrimp stir-fried with fresh Longjing tea leaves. The tea adds a subtle, fragrant bitterness that complements the sweet shrimp.",
        descriptionZh: "饱满河虾与新鲜龙井茶叶同炒。茶叶带来淡淡幽香的苦味，与鲜甜虾仁完美搭配。",
        priceRange: "¥68 – ¥128",
        priceRangeZh: "¥68 – ¥128",
      },
      {
        name: "Beggar's Chicken",
        nameZh: "叫花鸡",
        image: "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=800&h=600&fit=crop",
        description: "Whole chicken stuffed with herbs, wrapped in lotus leaves and clay, then slow-baked for hours. Crack open the clay shell at the table — dramatic and delicious.",
        descriptionZh: "整鸡填入香料，裹以荷叶和泥巴，慢烤数小时。在桌上敲开泥壳 — 仪式感满满，美味至极。",
        priceRange: "¥88 – ¥168",
        priceRangeZh: "¥88 – ¥168",
      },
      {
        name: "Pian'er Chuan Noodles",
        nameZh: "片儿川",
        image: "https://images.unsplash.com/photo-1555126634-323283e090fa?w=800&h=600&fit=crop",
        description: "Hangzhou's beloved noodle soup with bamboo shoots, pickled greens, and sliced pork. A humble, comforting bowl found in every local noodle shop.",
        descriptionZh: "杭州人最爱的面汤，配笋片、雪菜和肉丝。每家面馆都有的朴素暖心之味。",
        priceRange: "¥12 – ¥25",
        priceRangeZh: "¥12 – ¥25",
      },
    ],
    transport: [
      { mode: "Metro", modeZh: "地铁", description: "12 lines covering the city and reaching West Lake, train stations, and the airport. ¥2-8 per ride. English signage throughout.", descriptionZh: "12条线路覆盖全城，直达西湖、火车站和机场。每次¥2-8。全程英文标识。", icon: "🚇" },
      { mode: "Public Bike", modeZh: "公共自行车", description: "Hangzhou pioneered China's bike-sharing. Free for the first hour! Perfect for circling West Lake. Alipay scan to unlock.", descriptionZh: "杭州是中国共享单车的先驱。第一小时免费！环西湖骑行完美选择。支付宝扫码解锁。", icon: "🚲" },
      { mode: "DiDi / Taxi", modeZh: "滴滴/出租车", description: "Taxis start at ¥11. DiDi works well. Great for reaching tea plantations and Xixi Wetland.", descriptionZh: "出租车起步价¥11。滴滴好用。去茶园和西溪湿地很方便。", icon: "🚗" },
    ],
  },
  {
    slug: "kunming",
    name: "Kunming",
    nameZh: "昆明",
    tagline: "The Spring City — Eternal Springtime, Ethnic Mosaic & Gateway to Yunnan",
    taglineZh: "春城 — 四季如春、民族风情、云南门户",
    heroImage: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=1920&h=1080&fit=crop&q=80",
    quickFacts: [
      { label: "Best Season", labelZh: "最佳季节", value: "Year-round (Mar – Oct best)", valueZh: "全年皆宜（3-10月最佳）", icon: "🌺" },
      { label: "Avg Temperature", labelZh: "平均温度", value: "8°C – 24°C", valueZh: "8°C – 24°C", icon: "🌡️" },
      { label: "Currency", labelZh: "货币", value: "CNY (¥)", valueZh: "人民币 (¥)", icon: "💰" },
      { label: "Language", labelZh: "语言", value: "Mandarin & Yunnan dialect", valueZh: "普通话 & 云南话", icon: "🗣️" },
      { label: "Time Zone", labelZh: "时区", value: "UTC+8", valueZh: "UTC+8（东八区）", icon: "🕐" },
      { label: "Visa", labelZh: "签证", value: "144h Transit Visa-Free", valueZh: "144小时过境免签", icon: "🛂" },
    ],
    attractions: [
      {
        name: "Stone Forest",
        nameZh: "石林",
        image: "https://images.unsplash.com/photo-1558729785-c2c1bd32dfb5?w=800&h=600&fit=crop",
        description: "A UNESCO World Heritage karst landscape of towering limestone pillars covering 350 sq km. The Sani people call it 'the first wonder of the world.'",
        descriptionZh: "联合国教科文组织世界遗产，350平方公里的石灰岩柱群。撒尼人称之为「天下第一奇观」。",
        duration: "Half day (4-5 hours)",
        durationZh: "半天（4-5小时）",
        price: "¥130",
        priceZh: "¥130",
      },
      {
        name: "Dianchi Lake",
        nameZh: "滇池",
        image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&h=600&fit=crop",
        description: "Yunnan's largest lake, nicknamed the 'Sparkling Pearl.' Visit the Western Hills for panoramic views, or watch thousands of migratory seagulls in winter.",
        descriptionZh: "云南最大的湖泊，被称为「高原明珠」。游览西山俯瞰全景，或冬季观赏数千只候鸟红嘴鸥。",
        duration: "2-4 hours",
        durationZh: "2-4小时",
        price: "Free (cable car ¥70)",
        priceZh: "免费（缆车 ¥70）",
      },
      {
        name: "Yunnan Ethnic Village",
        nameZh: "云南民族村",
        image: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=800&h=600&fit=crop",
        description: "An open-air museum showcasing 25 of Yunnan's ethnic minorities. See traditional architecture, costumes, dances, and crafts — a cultural kaleidoscope.",
        descriptionZh: "露天博物馆展示云南25个少数民族。传统建筑、服饰、舞蹈和工艺品 — 文化万花筒。",
        duration: "3-4 hours",
        durationZh: "3-4小时",
        price: "¥90",
        priceZh: "¥90",
      },
      {
        name: "Green Lake Park",
        nameZh: "翠湖公园",
        image: "https://images.unsplash.com/photo-1529921879218-f99546d03caa?w=800&h=600&fit=crop",
        description: "Kunming's most beloved city park. Locals practice tai chi at dawn, play chess by the willows, and gather for outdoor dancing. Seagulls flock here Nov-Mar.",
        descriptionZh: "昆明人最喜爱的城市公园。清晨打太极、柳树下下棋、傍晚广场舞。11月至3月红嘴鸥成群而来。",
        duration: "1-2 hours",
        durationZh: "1-2小时",
        price: "Free",
        priceZh: "免费",
      },
      {
        name: "Dongchuan Red Land",
        nameZh: "东川红土地",
        image: "https://images.unsplash.com/photo-1620984438691-1d60f0777ecc?w=800&h=600&fit=crop",
        description: "Surreal rolling hills of deep red soil contrasting with green crops and blue skies. One of China's most photogenic landscapes, 2.5 hours from Kunming.",
        descriptionZh: "超现实的红色土壤丘陵与绿色农田和蓝天形成鲜明对比。中国最上镜的风景之一，距昆明2.5小时。",
        duration: "Full day trip",
        durationZh: "全天行程",
        price: "Free (transport ¥100-200)",
        priceZh: "免费（交通 ¥100-200）",
      },
    ],
    foods: [
      {
        name: "Crossing the Bridge Noodles",
        nameZh: "过桥米线",
        image: "https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?w=800&h=600&fit=crop",
        description: "Kunming's signature dish — a piping-hot chicken broth sealed with a layer of oil. Add raw meats, vegetables, and rice noodles tableside. They cook in seconds!",
        descriptionZh: "昆明招牌美食 — 滚烫鸡汤表面封一层油。在桌上加入生肉片、蔬菜和米线，瞬间烫熟！",
        priceRange: "¥15 – ¥50",
        priceRangeZh: "¥15 – ¥50",
      },
      {
        name: "Yunnan Hot Pot (Wild Mushroom)",
        nameZh: "野生菌火锅",
        image: "https://images.unsplash.com/photo-1617196034796-73dfa7b1fd56?w=800&h=600&fit=crop",
        description: "Yunnan's mountains produce 800+ mushroom species. This hotpot features rare wild fungi like matsutake, porcini, and chicken-of-the-woods. Earthy and addictive.",
        descriptionZh: "云南山区出产800多种菌类。火锅中有松茸、牛肝菌、鸡枞等珍稀野生菌。鲜美无比，让人上瘾。",
        priceRange: "¥80 – ¥200 per person",
        priceRangeZh: "¥80 – ¥200/人",
      },
      {
        name: "Erkuai (Rice Cake)",
        nameZh: "饵块",
        image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=600&fit=crop",
        description: "Chewy rice cakes grilled or stir-fried with chili, pickled vegetables, and ham. A Yunnan breakfast staple — find it at every morning street stall.",
        descriptionZh: "弹牙的饵块可烤可炒，配辣椒、腌菜和火腿。云南早餐必备 — 每个早点摊都有。",
        priceRange: "¥5 – ¥15",
        priceRangeZh: "¥5 – ¥15",
      },
      {
        name: "Xuanwei Ham",
        nameZh: "宣威火腿",
        image: "https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&h=600&fit=crop",
        description: "Yunnan's answer to prosciutto — dry-cured for 1-3 years at altitude. Rich, nutty, and slightly sweet. Try it steamed, in soup, or with mooncakes.",
        descriptionZh: "云南版的火腿 — 在高海拔地区腌制1-3年。浓郁、坚果香、微甜。蒸食、煮汤或配月饼皆宜。",
        priceRange: "¥30 – ¥80",
        priceRangeZh: "¥30 – ¥80",
      },
      {
        name: "Rose Cake",
        nameZh: "鲜花饼",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop",
        description: "Flaky pastries filled with sweet rose petal jam. Kunming's most popular souvenir — Jiahua is the most famous brand. Best eaten warm!",
        descriptionZh: "酥脆的饼皮包裹甜蜜的玫瑰花馅。昆明最受欢迎的伴手礼 — 嘉华是最知名品牌。趁热吃最好！",
        priceRange: "¥3 – ¥8 each",
        priceRangeZh: "¥3 – ¥8/个",
      },
    ],
    transport: [
      { mode: "Metro", modeZh: "地铁", description: "6 lines covering the city center, train station, and airport. ¥2-7 per ride. Clean and modern.", descriptionZh: "6条线路覆盖市中心、火车站和机场。每次¥2-7。干净现代。", icon: "🚇" },
      { mode: "High-Speed Rail", modeZh: "高铁", description: "HSR connects Kunming to Dali (2h), Lijiang, and even Laos! Kunming South Station is the hub.", descriptionZh: "高铁连接昆明到大理（2小时）、丽江，甚至老挝！昆明南站是枢纽。", icon: "🚄" },
      { mode: "DiDi / Taxi", modeZh: "滴滴/出租车", description: "Taxis start at ¥8. Affordable and easy. Essential for reaching Stone Forest and Red Land.", descriptionZh: "出租车起步价¥8。实惠方便。去石林和红土地必备。", icon: "🚗" },
    ],
  },
  {
    slug: "lhasa",
    name: "Lhasa",
    nameZh: "拉萨",
    tagline: "The Roof of the World — Sacred Palaces, Tibetan Spirituality & Vast Skies",
    taglineZh: "世界屋脊 — 神圣宫殿、藏传佛教与辽阔天空",
    heroImage: "https://images.unsplash.com/photo-1609073575309-f6d1aa4b07c2?w=1920&h=1080&fit=crop&q=80",
    quickFacts: [
      { label: "Best Season", labelZh: "最佳季节", value: "Jun – Sep (avoid monsoon)", valueZh: "6-9月（避开雨季）", icon: "☀️" },
      { label: "Altitude", labelZh: "海拔", value: "3,650m (11,975 ft)", valueZh: "3,650米", icon: "⛰️" },
      { label: "Currency", labelZh: "货币", value: "CNY (¥)", valueZh: "人民币 (¥)", icon: "💰" },
      { label: "Language", labelZh: "语言", value: "Tibetan & Mandarin", valueZh: "藏语 & 普通话", icon: "🗣️" },
      { label: "Time Zone", labelZh: "时区", value: "UTC+8 (sunset ~9PM!)", valueZh: "UTC+8（日落约晚9点！）", icon: "🕐" },
      { label: "Permit", labelZh: "许可证", value: "Tibet Travel Permit required", valueZh: "需办理入藏函", icon: "📋" },
    ],
    attractions: [
      {
        name: "Potala Palace",
        nameZh: "布达拉宫",
        image: "https://images.unsplash.com/photo-1609073575309-f6d1aa4b07c2?w=800&h=600&fit=crop",
        description: "The iconic 13-story palace perched at 3,700m — former winter residence of the Dalai Lama. 1,000 rooms filled with murals, statues, and sacred scriptures.",
        descriptionZh: "标志性的13层宫殿矗立在海拔3700米 — 达赖喇嘛的冬宫。1000个房间满是壁画、佛像和经文。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "¥200 (peak) / ¥100 (off-season)",
        priceZh: "¥200（旺季）/ ¥100（淡季）",
      },
      {
        name: "Jokhang Temple",
        nameZh: "大昭寺",
        image: "https://images.unsplash.com/photo-1591018653367-e685d3019875?w=800&h=600&fit=crop",
        description: "The spiritual heart of Tibet — pilgrims prostrate around its walls daily. Founded in 647 AD, it houses a sacred Jowo Shakyamuni statue brought from Nepal.",
        descriptionZh: "西藏的精神中心 — 朝圣者每天绕寺磕长头。始建于公元647年，供奉着从尼泊尔迎来的释迦牟尼12岁等身像。",
        duration: "1-2 hours",
        durationZh: "1-2小时",
        price: "¥85",
        priceZh: "¥85",
      },
      {
        name: "Barkhor Street",
        nameZh: "八廓街",
        image: "https://images.unsplash.com/photo-1564769662533-4f00a87b4056?w=800&h=600&fit=crop",
        description: "The ancient circular pilgrim path around Jokhang Temple. Bustling with prayer wheel-spinning pilgrims, incense, and stalls selling Tibetan crafts and turquoise.",
        descriptionZh: "大昭寺周围古老的朝圣转经路。转经筒的朝圣者、袅袅藏香和售卖藏族工艺品与绿松石的摊位热闹非凡。",
        duration: "1-3 hours",
        durationZh: "1-3小时",
        price: "Free",
        priceZh: "免费",
      },
      {
        name: "Sera Monastery",
        nameZh: "色拉寺",
        image: "https://images.unsplash.com/photo-1565018045502-44ab3db18c2a?w=800&h=600&fit=crop",
        description: "Famous for its daily monk debates (3PM weekdays) — monks clap, shout, and gesture dramatically to test Buddhist philosophy. A unique spectacle.",
        descriptionZh: "以每日辩经闻名（工作日下午3点）— 僧人击掌、高喊、手势激烈地辩论佛教哲学。独特的奇观。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "¥50",
        priceZh: "¥50",
      },
      {
        name: "Namtso Lake",
        nameZh: "纳木错",
        image: "https://images.unsplash.com/photo-1583417319070-4a69db38a482?w=800&h=600&fit=crop",
        description: "One of the world's highest saltwater lakes at 4,718m. Stunning turquoise waters backed by snow-capped Nyenchen Tanglha mountains. A sacred Tibetan lake.",
        descriptionZh: "世界最高的咸水湖之一，海拔4718米。碧蓝湖水背靠念青唐古拉雪山。藏族圣湖。",
        duration: "Full day or overnight",
        durationZh: "一整天或过夜",
        price: "¥120 (transport extra)",
        priceZh: "¥120（交通另计）",
      },
    ],
    foods: [
      {
        name: "Yak Butter Tea",
        nameZh: "酥油茶",
        image: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?w=800&h=600&fit=crop",
        description: "Salty, creamy tea made with yak butter and brick tea, churned together. Essential at altitude — locals drink 30+ cups a day. An acquired taste for most visitors!",
        descriptionZh: "用牦牛酥油和砖茶搅拌而成的咸味奶茶。高海拔必备 — 当地人每天喝30多杯。对大多数游客来说需要适应！",
        priceRange: "¥5 – ¥15",
        priceRangeZh: "¥5 – ¥15",
      },
      {
        name: "Tsampa",
        nameZh: "糌粑",
        image: "https://images.unsplash.com/photo-1496116218417-1a781b1c416c?w=800&h=600&fit=crop",
        description: "The Tibetan staple — roasted barley flour mixed with butter tea and kneaded into balls by hand. High-energy, portable, and deeply tied to nomadic culture.",
        descriptionZh: "藏族主食 — 青稞炒面与酥油茶混合，用手捏成团。高能量、便携，与游牧文化紧密相连。",
        priceRange: "¥5 – ¥10",
        priceRangeZh: "¥5 – ¥10",
      },
      {
        name: "Yak Meat Momos",
        nameZh: "牦牛肉饺子",
        image: "https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?w=800&h=600&fit=crop",
        description: "Tibetan dumplings filled with spiced yak meat, onions, and garlic. Steamed or fried, served with chili sauce. More robust than Chinese dumplings.",
        descriptionZh: "藏式饺子，包裹调味牦牛肉、洋葱和大蒜。蒸或煎，配辣椒酱。比中式饺子更有嚼劲。",
        priceRange: "¥15 – ¥30",
        priceRangeZh: "¥15 – ¥30",
      },
      {
        name: "Sweet Tea",
        nameZh: "甜茶",
        image: "https://images.unsplash.com/photo-1582450871972-ab5ca641643d?w=800&h=600&fit=crop",
        description: "Milky, sweetened black tea — Lhasa's social drink. Sit in a local teahouse for hours watching life go by. Leave money on the table and they refill endlessly.",
        descriptionZh: "加奶加糖的红茶 — 拉萨的社交饮品。在茶馆坐上几小时看人来人往。把钱放桌上，续杯不断。",
        priceRange: "¥0.5 – ¥3 per glass",
        priceRangeZh: "¥0.5 – ¥3/杯",
      },
      {
        name: "Yak Yogurt",
        nameZh: "牦牛酸奶",
        image: "https://images.unsplash.com/photo-1582564286960-0a4a7ffe5e42?w=800&h=600&fit=crop",
        description: "Thick, tangy yogurt made from yak milk, topped with a spoonful of sugar. Creamier and more flavorful than regular yogurt. Found at Barkhor Street stalls.",
        descriptionZh: "用牦牛奶制成的浓稠酸奶，上面撒一勺糖。比普通酸奶更浓郁、更有味。八廓街摊位上随处可见。",
        priceRange: "¥5 – ¥10",
        priceRangeZh: "¥5 – ¥10",
      },
    ],
    transport: [
      { mode: "City Bus", modeZh: "公交", description: "¥1 flat fare. Covers all major sites. Bus 13 runs between Potala Palace and Sera Monastery.", descriptionZh: "统一票价¥1。覆盖所有主要景点。13路公交连接布达拉宫和色拉寺。", icon: "🚌" },
      { mode: "Bicycle / E-bike", modeZh: "自行车/电动车", description: "Flat city center is bikeable but watch altitude! Rent an e-bike for ¥50-80/day. Good for Barkhor area.", descriptionZh: "平坦的市中心适合骑行但注意高反！租电动车¥50-80/天。八廓街周围很方便。", icon: "🚲" },
      { mode: "Guided Tours", modeZh: "跟团游", description: "Required for most Tibet itineraries outside Lhasa. Your travel agent arranges permits, driver, and guide.", descriptionZh: "拉萨以外的行程大多需要跟团。旅行社安排许可证、司机和导游。", icon: "🚐" },
    ],
  },
  {
    slug: "harbin",
    name: "Harbin",
    nameZh: "哈尔滨",
    tagline: "Ice City — World-Famous Ice Festival, Russian Heritage & Winter Wonderland",
    taglineZh: "冰城 — 世界级冰雪节、俄罗斯风情与冬日仙境",
    heroImage: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=1920&h=1080&fit=crop&q=80",
    quickFacts: [
      { label: "Best Season", labelZh: "最佳季节", value: "Dec – Feb (ice festival!)", valueZh: "12-2月（冰雪节！）", icon: "❄️" },
      { label: "Winter Temp", labelZh: "冬季温度", value: "-25°C – -10°C", valueZh: "-25°C – -10°C", icon: "🌡️" },
      { label: "Currency", labelZh: "货币", value: "CNY (¥)", valueZh: "人民币 (¥)", icon: "💰" },
      { label: "Language", labelZh: "语言", value: "Mandarin (Dongbei dialect)", valueZh: "普通话（东北话）", icon: "🗣️" },
      { label: "Time Zone", labelZh: "时区", value: "UTC+8", valueZh: "UTC+8（东八区）", icon: "🕐" },
      { label: "Visa", labelZh: "签证", value: "144h Transit Visa-Free", valueZh: "144小时过境免签", icon: "🛂" },
    ],
    attractions: [
      {
        name: "Harbin Ice & Snow World",
        nameZh: "哈尔滨冰雪大世界",
        image: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&h=600&fit=crop",
        description: "The world's largest ice and snow festival — massive illuminated ice castles, slides, and sculptures carved from Songhua River ice. Open Dec-Feb.",
        descriptionZh: "世界最大的冰雪节 — 巨型灯光冰城堡、冰滑梯和用松花江冰雕刻的冰雕。12-2月开放。",
        duration: "3-5 hours (evening best)",
        durationZh: "3-5小时（晚间最佳）",
        price: "¥300 (peak) / ¥180 (off-peak)",
        priceZh: "¥300（高峰期）/ ¥180（平时）",
      },
      {
        name: "Sun Island Snow Sculpture Expo",
        nameZh: "太阳岛雪博会",
        image: "https://images.unsplash.com/photo-1506970845246-9f0c8f05aaec?w=800&h=600&fit=crop",
        description: "A daytime complement to Ice World — enormous snow sculptures up to 30m tall, created by artists from around the world. Best visited in morning light.",
        descriptionZh: "冰雪大世界的白天版 — 高达30米的巨型雪雕，由世界各地艺术家创作。晨光中参观最佳。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "¥240",
        priceZh: "¥240",
      },
      {
        name: "Saint Sophia Cathedral",
        nameZh: "圣索菲亚教堂",
        image: "https://images.unsplash.com/photo-1553701879-85b5abb7b76d?w=800&h=600&fit=crop",
        description: "A stunning Byzantine-style Russian Orthodox cathedral built in 1907. Now a museum and Harbin's most iconic landmark. Beautiful when snow-covered.",
        descriptionZh: "1907年建造的华美拜占庭风格俄罗斯东正教堂。现为博物馆，哈尔滨最标志性的地标。雪中更美。",
        duration: "30 min – 1 hour",
        durationZh: "30分钟 – 1小时",
        price: "¥15",
        priceZh: "¥15",
      },
      {
        name: "Central Avenue (Zhongyang Street)",
        nameZh: "中央大街",
        image: "https://images.unsplash.com/photo-1581985673275-71a01a8a0a8f?w=800&h=600&fit=crop",
        description: "A 1.4km cobblestone pedestrian street lined with early 20th-century European architecture — Art Nouveau, Baroque, and Renaissance. Harbin's main promenade.",
        descriptionZh: "1.4公里的鹅卵石步行街，两旁是20世纪初的欧式建筑 — 新艺术、巴洛克和文艺复兴风格。哈尔滨的主要步行大道。",
        duration: "1-2 hours",
        durationZh: "1-2小时",
        price: "Free",
        priceZh: "免费",
      },
      {
        name: "Siberian Tiger Park",
        nameZh: "东北虎林园",
        image: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&h=600&fit=crop",
        description: "The world's largest Siberian tiger breeding center with 1,000+ tigers. Take a bus through the enclosure and see tigers up close. Also has ligers and white tigers.",
        descriptionZh: "世界最大的东北虎繁殖基地，1000多只老虎。乘坐观光车穿行围场，近距离观看老虎。还有狮虎兽和白虎。",
        duration: "2-3 hours",
        durationZh: "2-3小时",
        price: "¥100",
        priceZh: "¥100",
      },
    ],
    foods: [
      {
        name: "Harbin Red Sausage",
        nameZh: "哈尔滨红肠",
        image: "https://images.unsplash.com/photo-1643123446139-1b05e90e3f5e?w=800&h=600&fit=crop",
        description: "Smoked pork sausage with a Russian influence — crispy casing, garlicky, slightly smoky. Churin brand is the most famous. Buy them on Central Avenue.",
        descriptionZh: "俄式风味的烟熏猪肉肠 — 脆皮、蒜香、微微烟熏味。秋林品牌最著名。中央大街上即可购买。",
        priceRange: "¥15 – ¥35",
        priceRangeZh: "¥15 – ¥35",
      },
      {
        name: "Guobaorou (Sweet & Sour Pork)",
        nameZh: "锅包肉",
        image: "https://images.unsplash.com/photo-1607532941433-304659e8198a?w=800&h=600&fit=crop",
        description: "Harbin's most famous dish — crispy-fried pork slices in a tangy sweet-and-sour sauce with scallions. Crunchy outside, tender inside. Totally addictive.",
        descriptionZh: "哈尔滨最著名的菜 — 酥脆炸猪肉片裹以酸甜酱汁配葱花。外酥里嫩，让人欲罢不能。",
        priceRange: "¥35 – ¥58",
        priceRangeZh: "¥35 – ¥58",
      },
      {
        name: "Frozen Pears",
        nameZh: "冻梨",
        image: "https://images.unsplash.com/photo-1576577445504-6af96477db52?w=800&h=600&fit=crop",
        description: "Black-skinned frozen pears — a Dongbei winter tradition. Soak in cold water to thaw slightly, then bite into the icy, sweet flesh. Street stalls sell them everywhere.",
        descriptionZh: "黑皮冻梨 — 东北冬季传统。用冷水稍微化冻，然后咬一口冰甜果肉。街头摊位到处都卖。",
        priceRange: "¥5 – ¥10",
        priceRangeZh: "¥5 – ¥10",
      },
      {
        name: "Dalieba (Russian Bread)",
        nameZh: "大列巴",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=600&fit=crop",
        description: "A massive round Russian-style sourdough bread, often 2kg+. Dense, slightly sour, great with butter or red sausage. A Harbin specialty since the early 1900s.",
        descriptionZh: "巨大的圆形俄式酸面包，常重2公斤以上。紧实、微酸，配黄油或红肠绝佳。1900年代起就是哈尔滨特产。",
        priceRange: "¥20 – ¥38 per loaf",
        priceRangeZh: "¥20 – ¥38/个",
      },
      {
        name: "Disanxian (Three Earth Delights)",
        nameZh: "地三鲜",
        image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&h=600&fit=crop",
        description: "A Dongbei classic — fried potatoes, eggplant, and green peppers in a savory soy-garlic sauce. Simple, hearty, and the ultimate comfort food up north.",
        descriptionZh: "东北经典菜 — 炸土豆、茄子和青椒配酱油蒜汁。简单、丰盛，北方的终极治愈美食。",
        priceRange: "¥20 – ¥35",
        priceRangeZh: "¥20 – ¥35",
      },
    ],
    transport: [
      { mode: "Metro", modeZh: "地铁", description: "3 lines covering the main city. ¥2-5 per ride. Line 1 connects train station to Central Avenue area.", descriptionZh: "3条线路覆盖市区。每次¥2-5。1号线连接火车站到中央大街区域。", icon: "🚇" },
      { mode: "Bus", modeZh: "公交", description: "Extensive but cold waits in winter! Bus lines reach Ice & Snow World and Sun Island. ¥1-2 per ride.", descriptionZh: "覆盖广但冬天等车冷！公交可达冰雪大世界和太阳岛。每次¥1-2。", icon: "🚌" },
      { mode: "DiDi / Taxi", modeZh: "滴滴/出租车", description: "Essential in winter — taxis start at ¥8. DiDi reliable. Keep warm while getting around!", descriptionZh: "冬天必备 — 出租车起步价¥8。滴滴可靠。出行保暖第一！", icon: "🚗" },
    ],
  },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return CITIES.map((c) => c.slug);
}
