export interface TripTemplate {
  id: string;
  title: string;
  cities: string[];
  days: number;
  theme: "culture" | "food" | "nature" | "adventure" | "classic" | "photography";
  highlights: string[];
  budgetRange: string;
  coverImage: string;
  description: string;
}

export const TRIP_TEMPLATES: TripTemplate[] = [
  {
    id: "beijing-classic-3d",
    title: "Beijing 3-Day Classic",
    cities: ["Beijing"],
    days: 3,
    theme: "classic",
    highlights: ["Great Wall at Mutianyu", "Forbidden City", "Temple of Heaven", "Peking Duck dinner"],
    budgetRange: "$300-500",
    coverImage: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&h=600&fit=crop",
    description: "The essential Beijing experience — imperial palaces, ancient walls, and legendary cuisine. Perfect for first-timers with limited time.",
  },
  {
    id: "shanghai-modern-5d",
    title: "Shanghai Modern & Traditional",
    cities: ["Shanghai", "Suzhou"],
    days: 5,
    theme: "culture",
    highlights: ["The Bund night walk", "Yu Garden", "French Concession cycling", "Suzhou classical gardens day trip"],
    budgetRange: "$400-700",
    coverImage: "https://images.unsplash.com/photo-1545893835-abaa50cbe628?w=800&h=600&fit=crop",
    description: "Where colonial-era charm meets futuristic skylines. Explore Shanghai's dual personality, then escape to the garden city of Suzhou.",
  },
  {
    id: "silk-road-7d",
    title: "Silk Road 7-Day Adventure",
    cities: ["Xi'an", "Dunhuang", "Turpan", "Urumqi"],
    days: 7,
    theme: "adventure",
    highlights: ["Terracotta Warriors", "Mogao Caves", "Singing Sand Dunes", "Kashgar Grand Bazaar"],
    budgetRange: "$800-1200",
    coverImage: "https://images.unsplash.com/photo-1725933014999-e70ae6e57375?w=800&h=600&fit=crop",
    description: "Retrace the ancient trade route through desert oases, cave temples, and the diverse cultures of western China.",
  },
  {
    id: "chengdu-food-4d",
    title: "Chengdu Food Paradise",
    cities: ["Chengdu"],
    days: 4,
    theme: "food",
    highlights: ["Giant Panda Base", "Sichuan hotpot crawl", "Street food on Jinli", "Cooking class & tea ceremony"],
    budgetRange: "$250-450",
    coverImage: "https://images.unsplash.com/photo-1564349683136-77e08dba1ef7?w=800&h=600&fit=crop",
    description: "Taste the fire of Sichuan cuisine, cuddle pandas, and discover why Chengdu is China's most livable city.",
  },
  {
    id: "yunnan-nature-6d",
    title: "Yunnan Nature Trek",
    cities: ["Kunming", "Dali", "Lijiang", "Shangri-La"],
    days: 6,
    theme: "nature",
    highlights: ["Erhai Lake cycling", "Tiger Leaping Gorge", "Jade Dragon Snow Mountain", "Old town sunset walks"],
    budgetRange: "$500-800",
    coverImage: "https://images.unsplash.com/photo-1513415277900-a62401e19be4?w=800&h=600&fit=crop",
    description: "Snow-capped peaks, turquoise lakes, and ancient Naxi towns. Yunnan is China's most diverse and beautiful province.",
  },
  {
    id: "hongkong-weekend-3d",
    title: "Hong Kong Weekend Escape",
    cities: ["Hong Kong"],
    days: 3,
    theme: "classic",
    highlights: ["Victoria Peak at sunset", "Dim sum at Tim Ho Wan", "Star Ferry harbour crossing", "Temple Street night market"],
    budgetRange: "$400-600",
    coverImage: "https://images.unsplash.com/photo-1536599018102-9f803c140fc1?w=800&h=600&fit=crop",
    description: "Skyscrapers, harbour views, and the world's best dim sum. Hong Kong packs more per square mile than anywhere on Earth.",
  },
  {
    id: "xian-ancient-5d",
    title: "Xi'an Ancient Capital",
    cities: ["Xi'an"],
    days: 5,
    theme: "culture",
    highlights: ["Terracotta Warriors full day", "City Wall cycling", "Muslim Quarter food crawl", "Wild Goose Pagoda"],
    budgetRange: "$300-550",
    coverImage: "https://images.unsplash.com/photo-1725933014999-e70ae6e57375?w=800&h=600&fit=crop",
    description: "13 dynasties called Xi'an home. Walk where emperors walked, eat where the Silk Road traders ate.",
  },
  {
    id: "guilin-landscape-4d",
    title: "Guilin Karst Landscape",
    cities: ["Guilin", "Yangshuo"],
    days: 4,
    theme: "nature",
    highlights: ["Li River bamboo raft cruise", "Yangshuo countryside cycling", "Reed Flute Cave", "Longji Rice Terraces"],
    budgetRange: "$350-600",
    coverImage: "https://images.unsplash.com/photo-1759322451543-68c2217e9046?w=800&h=600&fit=crop",
    description: "The landscape on the ¥20 note. Guilin's karst peaks and the Li River are the stuff of Chinese paintings.",
  },
  {
    id: "trans-china-rail-10d",
    title: "Trans-China Rail Journey",
    cities: ["Beijing", "Xi'an", "Chengdu", "Kunming", "Shanghai"],
    days: 10,
    theme: "adventure",
    highlights: ["5 cities by bullet train", "Great Wall to pandas", "Sichuan spice to Yunnan charm", "East meets West"],
    budgetRange: "$1000-1800",
    coverImage: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&h=600&fit=crop",
    description: "Cross China by high-speed rail — 5 cities, 10 days, infinite memories. The ultimate first-timer's grand tour.",
  },
  {
    id: "first-timer-china-7d",
    title: "First Timer's China",
    cities: ["Beijing", "Xi'an", "Shanghai"],
    days: 7,
    theme: "classic",
    highlights: ["Great Wall & Forbidden City", "Terracotta Warriors", "The Bund & Yu Garden", "Bullet train experience"],
    budgetRange: "$700-1100",
    coverImage: "https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=800&h=600&fit=crop",
    description: "The perfect introduction to China. Hit all the iconic spots, ride the world's fastest trains, and eat your way through three legendary cities.",
  },
  {
    id: "yunnan-adventure-10d",
    title: "Yunnan Adventure",
    cities: ["Kunming", "Dali", "Lijiang", "Shangri-La"],
    days: 10,
    theme: "adventure",
    highlights: ["Tiger Leaping Gorge trek", "Erhai Lake cycling & Bai villages", "Jade Dragon Snow Mountain", "Songzanlin Monastery & Tibetan culture"],
    budgetRange: "$700-1200",
    coverImage: "https://images.unsplash.com/photo-1513415277900-a62401e19be4?w=800&h=600&fit=crop",
    description: "Ten days through China's most diverse province — from the Spring City to Tibetan plateaus. Hike gorges, cycle lakesides, and discover 25 ethnic cultures.",
  },
  {
    id: "harbin-winter-5d",
    title: "Harbin Winter Wonderland",
    cities: ["Harbin"],
    days: 5,
    theme: "culture",
    highlights: ["Ice & Snow World festival", "Saint Sophia Cathedral", "Siberian Tiger Park", "Russian-style Central Street food crawl"],
    budgetRange: "$350-600",
    coverImage: "https://images.unsplash.com/photo-1548919973-5cef591cdbc9?w=800&h=600&fit=crop",
    description: "Experience the world's largest ice festival in China's coldest city. Russian-era architecture, ice sculptures taller than buildings, and Dongbei comfort food.",
  },
  {
    id: "tibet-spiritual-7d",
    title: "Tibet Spiritual Journey",
    cities: ["Lhasa", "Shigatse", "Everest Base Camp"],
    days: 7,
    theme: "adventure",
    highlights: ["Potala Palace sunrise", "Jokhang Temple kora walk", "Tashilhunpo Monastery", "Everest Base Camp sunset"],
    budgetRange: "$1200-2000",
    coverImage: "https://images.unsplash.com/photo-1609073575309-f6d1aa4b07c2?w=800&h=600&fit=crop",
    description: "A sacred journey across the Roof of the World. Walk with pilgrims in Lhasa, cross the Tibetan plateau, and stand before Everest at 5,200 meters.",
  },
  {
    id: "hangzhou-tea-3d",
    title: "Hangzhou Tea & Culture",
    cities: ["Hangzhou"],
    days: 3,
    theme: "culture",
    highlights: ["West Lake sunset boat cruise", "Longjing tea plantation visit", "Lingyin Temple & Feilai Feng", "Hefang Street night market"],
    budgetRange: "$200-400",
    coverImage: "https://images.unsplash.com/photo-1599571234909-29ed5d1321d6?w=800&h=600&fit=crop",
    description: "Marco Polo called it the finest city in the world. Three days of pagoda-dotted lakes, hand-picked tea on misty hills, and 1,700 years of Buddhist art.",
  },
  {
    id: "grand-china-21d",
    title: "Grand China Tour",
    cities: ["Beijing", "Xi'an", "Chengdu", "Guilin", "Hong Kong"],
    days: 21,
    theme: "classic",
    highlights: ["Great Wall & Forbidden City", "Terracotta Warriors & Muslim Quarter", "Giant Pandas & Sichuan hotpot", "Li River cruise & Victoria Peak"],
    budgetRange: "$2000-3500",
    coverImage: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&h=600&fit=crop",
    description: "The ultimate three-week odyssey across China — five legendary cities, imperial palaces, karst mountains, spicy cuisine, and a harbour skyline finale.",
  },
  {
    id: "foodie-paradise-7d",
    title: "Foodie's Paradise",
    cities: ["Chengdu", "Chongqing", "Guangzhou", "Hong Kong"],
    days: 7,
    theme: "food",
    highlights: ["Sichuan hotpot & street food crawl", "Chongqing night noodles & river views", "Cantonese dim sum masterclass", "Hong Kong dai pai dong & roast goose"],
    budgetRange: "$600-1000",
    coverImage: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&h=600&fit=crop",
    description: "Four cities, four cuisines, seven days of fire and flavor. From mouth-numbing Sichuan peppercorn to silky Cantonese har gow — eat your way across China.",
  },
  {
    id: "ancient-capital-trail-10d",
    title: "Ancient Capital Trail",
    cities: ["Beijing", "Xi'an", "Luoyang", "Nanjing", "Hangzhou"],
    days: 10,
    theme: "culture",
    highlights: ["Forbidden City & Summer Palace", "Longmen Grottoes & Shaolin Temple", "Ming Dynasty city walls & Sun Yat-sen Mausoleum", "West Lake & Six Harmonies Pagoda"],
    budgetRange: "$900-1500",
    coverImage: "https://images.unsplash.com/photo-1725933014999-e70ae6e57375?w=800&h=600&fit=crop",
    description: "Walk through 3,000 years of Chinese civilization — five ancient capitals, each a former seat of empire. Palaces, grottoes, city walls, and lakeside pagodas.",
  },
  {
    id: "photography-china-14d",
    title: "Photography China",
    cities: ["Zhangjiajie", "Guilin", "Kunming", "Lhasa"],
    days: 14,
    theme: "photography",
    highlights: ["Avatar Hallelujah Mountains at dawn", "Li River cormorant fisherman sunrise", "Yuanyang rice terraces golden hour", "Potala Palace blue-hour reflection"],
    budgetRange: "$1500-2500",
    coverImage: "https://images.unsplash.com/photo-1759322451543-68c2217e9046?w=800&h=600&fit=crop",
    description: "Two weeks chasing China's most photogenic landscapes. Floating sandstone pillars, mirror-still rivers, cascading rice terraces, and the Roof of the World.",
  },
];

export const THEME_LABELS: Record<string, string> = {
  all: "All",
  classic: "Classic",
  food: "Food",
  nature: "Nature",
  adventure: "Adventure",
  culture: "Culture",
  photography: "Photography",
};

export const THEME_EMOJIS: Record<string, string> = {
  all: "🌏",
  classic: "🏛️",
  food: "🍜",
  nature: "🌿",
  adventure: "🧗",
  culture: "🎎",
  photography: "📷",
};
